export const FETCH_CATEGORIES_BEGIN = "FETCH_CATEGORIES_BEGIN";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";

export const FETCH_CATEGORIES_PRODUCTS_BEGIN = "FETCH_CATEGORIES_PRODUCTS_BEGIN";
export const FETCH_CATEGORIES_PRODUCTS_SUCCESS = "FETCH_CATEGORIES_PRODUCTS_SUCCESS";
export const FETCH_CATEGORIES_PRODUCTS_FAILURE = "FETCH_CATEGORIES_PRODUCTS_FAILURE";