export const FETCH_CATEGORIES_BEGIN = "FETCH_CATEGORIES_BEGIN";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";

export const FETCH_CATEGORIES_PRODUCTS_BEGIN = "FETCH_CATEGORIES_PRODUCTS_BEGIN";
export const FETCH_CATEGORIES_PRODUCTS_SUCCESS = "FETCH_CATEGORIES_PRODUCTS_SUCCESS";
export const FETCH_CATEGORIES_PRODUCTS_FAILURE = "FETCH_CATEGORIES_PRODUCTS_FAILURE";

export const FETCH_PRODUCT_BEGIN = "FETCH_PRODUCT_BEGIN";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE";

export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const ADD_REPEAT_PRODUCT = "ADD_REPEAT_PRODUCT";

export const CREATE_SHIPPING = "CREATE_SHIPPING";
export const CREATE_PAYMENT = "CREATE_PAYMENT";
export const CREATE_ORDER = "CREATE_ORDER";



